# spark-operator-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: spark-operator
  namespace: spark-operator
roleRef:
  kind: ClusterRole
  name: spark-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

